name: rag-research-iq-env
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pip
  - pip:
      - langchain
      - langchain-community
      - langchain-chroma
      - langchain-groq
      - langchain-huggingface
      - chromadb
      - unstructured
      - streamlit
      - python-dotenv
      - sentence-transformers
      - pydantic
      - requests
      - uuid